#!/bin/bash
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'

function create_user() {
  echo -e "\e[36m------------------------------------------\e[0m"
        read -p "※ Enter Username : " uname
        egrep "^$uname:" /etc/passwd >/dev/null
        if [ $? -eq 0 ]; then
        echo -e "Username \e[31m$uname\e[0m Already Register ..!"
        exit 1
        else
        read -p "※ Enter Password : " pass
        read -p "※ Total Days To Exp Or Y-M-D : " expdate
        today="$(date +"%Y-%m-%d")"
        expire=$(date -d "$expdate days" +"%Y-%m-%d")
        useradd -M -N -s /bin/false -e $expire $uname
        echo $uname:$pass | chpasswd
clear
        echo " ";
        echo " ";
        echo " ";
        echo -e " \e[36m※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※
 ※                                 ※
 ※\e[0m  WELCOME! \e[36m※
 ※                                 ※
 ※\e[0m  VPS By DAVID ARMSTRONG        \e[36m※
 ※                                 ※
 ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※\e[0m";
        echo "
 ◎ Details For Your Account ◎";
        echo " ";
        echo -e "  \e[34m※\e[0m Username   : \e[34m$uname\e[0m";
        echo -e "  \e[34m※\e[0m Password   : \e[34m$pass\e[0m";
        echo -e "  \e[32m※\e[0m Expired On : \e[32m$(date -d "$expdate days" +"%d-%m-%Y")\e[0m";
        echo " ";
        echo " ";
        echo " ";
        echo " ";
        fi
}
